version: '3.8'
services:

  neutron-first:
    image: neutron-node
    container_name: neutron-first
    volumes:
      - first:/opt/neutron/data
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
      - 9090:9090
    environment:
      - CHAINID=test-1
      - RUN_BACKGROUND=0
    networks:
      - hack

  neutron-second:
    image: neutron-node
    container_name: neutron-second
    volumes:
      - second:/opt/neutron/data
    ports:
      - 3317:1317
      - 36657:26657
      - 36656:26656
      - 39090:9090
    environment:
      - CHAINID=test-2
      - RUN_BACKGROUND=0
    networks:
      - hack

  hermes:
    build:
      context: ./dockerbuilds
    container_name: hermes
    depends_on:
      - "neutron-first"
      - "neutron-second"
    ports:
      - 8000:8080
    environment:
      - NODE_ENV=production
    networks:
      - hack

volumes:
  first:
    name: neutron-first-data
    external: false
  second:
    name: neutron-second-data
    external: false

networks:
  hack:
    name: hack
    external: false